name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: npx nx-cloud@next start-ci-run --stop-agents-after="build"
      - run: npm ci
      - run: npx nx run-many -t lint build --dte
      - run: npx nx-cloud@next stop-all-agents
